runtime: nodejs18
service: mcp-server

env_variables:
  NODE_ENV: production
  PORT: 8080

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10
  target_concurrent_requests: 100

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

handlers:
  - url: /.*
    script: auto
    secure: always 